Data:
  input_root_folder:  "ShapeNetMeshes/" # Top-Level folder for input model files
  output_root_folder: "RenderedImages/" # Top-Level folder for Output render images

Scene:
  x_size: 512 # Width of rendered output image in pixels
  y_size: 512 # Height of rendered output image in pixels

Lamp:
  lamp_energy:  0.75    # Energy of lamp; 1 = full energy, but can be higher as well
  lamp_color:   [1,1,1] # RGB values for light color
  lamp_type:    "HEMI"  # Type of light to use; See Blender docs for details

Camera:
  cam_fov:          10    # Field-of-View (in degrees)
  cam_theta_step:   10    # Angular Difference (in degrees) between two consecutive positions of the camera 
  cam_phi:          70    # "Elevation" angle of the camera